version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=HMS;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=True;"
    networks:
      - hmsnet
  frontend:
    build:
      context: ./patient-dashboard
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - hmsnet  
volumes:
  sqlvolume:

networks:
  hmsnet:
